import Navbar from "@/components/navbar/Navbar";
import "./globals.css";
import "bootstrap-icons/font/bootstrap-icons.css";
import "react-toastify/dist/ReactToastify.css";
import { ToastContainer } from "react-toastify";
import { Inter } from "next/font/google";
import Footer from "@/components/footer/Footer";
import { ThemeProvider } from "@/context/themeContext";
import AuthProvider from "@/components/authProvider/AuthProvider";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
	title: "Abdelazim",
	description: "Abdelazim Hassan Portfolio Website Generated by NextJS 13",
};

export default function RootLayout({ children }) {
	return (
		<html lang='en'>
			<body className={inter.className}>
				<ThemeProvider>
					<AuthProvider>
						<main className='container'>
							<Navbar />
							{children}
							<Footer />
						</main>
						<ToastContainer
							position='bottom-right'
							autoClose={3000}
							closeOnClick
							theme='colored'
						/>
					</AuthProvider>
				</ThemeProvider>
			</body>
		</html>
	);
}
